// File generated by FlutterFire CLI.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEmt8MmqkrTOwGd_zIAxj-L2fCc0cIZ3U',
    appId: '1:663620755530:web:328f2a3d1eb36ca38a06b3',
    messagingSenderId: '663620755530',
    projectId: 'cook-instead',
    authDomain: 'cook-instead.firebaseapp.com',
    databaseURL: 'https://cook-instead-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cook-instead.appspot.com',
    measurementId: 'G-P682278835',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbOna0DYOTnWnxuBG9k-nFSnBOR2fkwxk',
    appId: '1:663620755530:android:1fa5a1b65be9f0bb8a06b3',
    messagingSenderId: '663620755530',
    projectId: 'cook-instead',
    databaseURL: 'https://cook-instead-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cook-instead.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAx11NqGwRHofjCCpeI_0bdlhBfbFaOW5k',
    appId: '1:663620755530:ios:c32e71387a7a1ad48a06b3',
    messagingSenderId: '663620755530',
    projectId: 'cook-instead',
    databaseURL: 'https://cook-instead-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cook-instead.appspot.com',
    iosClientId: '663620755530-1esk6rq1e6bbeuqqov4or72amhastdrb.apps.googleusercontent.com',
    iosBundleId: 'com.example.cookInstead',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAx11NqGwRHofjCCpeI_0bdlhBfbFaOW5k',
    appId: '1:663620755530:ios:3b474da54b1343c88a06b3',
    messagingSenderId: '663620755530',
    projectId: 'cook-instead',
    databaseURL: 'https://cook-instead-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cook-instead.appspot.com',
    iosClientId: '663620755530-covnhi05en4ii6q9kjmmavqnnjnh1a3o.apps.googleusercontent.com',
    iosBundleId: 'com.example.cookInstead.RunnerTests',
  );
}
